compile:
	g++ -Werror main.cpp -o compiled

run:
	g++ -Werror main.cpp -o compiled && ./compiled

wrun:
	g++ -Werror main.cpp -o compiled && compiled.exe	

clear:
	rm compiled

wclear: 
	del compiled.exe
